# Data Analysis with Pandas

### Import and use Pandas

In [9]:
import pandas as pd

# create new series
number_series = pd.Series([1,2,3,4])
print(number_series)

# create new Data Frame
user_data_dict = {
    "Name":["Ram","Hari"],
    "Age": [20,23],
    "Address":["Kathmandu","Lalitpur"]
}
user_data = pd.DataFrame(user_data_dict)
user_data

0    1
1    2
2    3
3    4
dtype: int64

   Name  Age    Address
0   Ram   20  Kathmandu
1  Hari   23   Lalitpur

## Read data  from CSV, Excel and JSON file

### Read data from csv

In [10]:
import pandas as pd

student_csv_data = pd.read_csv('data/student-dataset.csv')
student_csv_data.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

### Save Pandas Dataframe to csv, excel and JSON file

In [11]:
import pandas as pd

# create new Data Frame
user_data = pd.DataFrame({
    "Name":["Ram","Hari"],
    "Age": [20,23],
    "Address":["Kathmandu","Lalitpur"]
})

user_data.to_csv('./data/user_data.csv')
user_data.to_excel('data/user_data.xlsx')
user_data.to_json('data/user_data.json')

## Basic Data Exploration

### Data Inspection

In [12]:
import pandas as pd
students = pd.read_csv('data/student-dataset.csv')
print(students.shape)
print(students.info())
students.describe()

(307, 16)
<class 'pandas.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  307 non-null    int64
 1   name                307 non-null    str
 2   nationality         307 non-null    str
 3   city                307 non-null    str
 4   latitude            307 non-null    float64
 5   longitude           307 non-null    float64
 6   gender              307 non-null    str
 7   ethnic.group        0 non-null      float64
 8   age                 307 non-null    int64
 9   english.grade       307 non-null    float64
 10  math.grade          307 non-null    float64
 11  sciences.grade      307 non-null    float64
 12  language.grade      307 non-null    float64
 13  portfolio.rating    307 non-null    int64
 14  coverletter.rating  307 non-null    float64
 15  refletter.rating    307 non-null    int64
dtypes: float64(8), int64(4), str(4)
memory usage: 38.5 KB
None

,id,latitude,longitude,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
count,307.000000,307.000000,307.000000,0.0,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,153.000000,32.863388,-64.539121,NaN,21.964169,3.369707,3.414332,3.446580,4.396417,3.986971,4.110749,4.188925
std,88.767487,13.498582,81.249146,NaN,1.248013,0.538724,0.476839,0.509081,0.996474,0.928749,0.823936,0.842193
min,0.000000,-33.450000,-123.130000,NaN,19.000000,1.500000,2.100000,1.400000,1.000000,1.000000,1.000000,1.000000
25%,76.500000,32.720000,-118.240000,NaN,21.000000,3.100000,3.100000,3.200000,4.000000,3.500000,4.000000,4.000000
50%,153.000000,34.390000,-99.140000,NaN,22.000000,3.500000,3.500000,3.600000,5.000000,4.000000,4.000000,4.000000
75%,229.500000,38.960000,-73.855000,NaN,23.000000,3.800000,3.800000,3.800000,5.000000,5.000000,5.000000,5.000000
max,306.000000,59.890000,139.750000,NaN,26.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000

# Data Selection and Indexing in Pandas
- ##### Basic Indexing
- ##### Label-based Indexing (.loc[])
- ##### Integer-Label-based Indexing (.iloc[])
- ##### Single Value Access (.at[], .iat[])

### Basic Indexing

In [13]:
# # Basic indexing
print(students['name'])          # Single column as a Series
new_std_data = students[['id','name','nationality']]
print(new_std_data)   # Multiple columns as a DataFrame

# # # Slicing rows
first_10_rows = students[0:10]
print(first_10_rows) # only first row (dataframe)
last_five_rows = students[302:307].copy()
print(last_five_rows)          # Rows from index 30 to last index (dataframe)

0              Kiana Lor
1         Joshua Lonaker
2          Dakota Blanco
3        Natasha Yarusso
4         Brooke Cazares
             ...
302          Austin Haas
303      Madison Fithian
304    Zachary Mulvahill
305     Eliana Michelsen
306      Dane Whittemore
Name: name, Length: 307, dtype: str
      id               name               nationality
0      0          Kiana Lor                     China
1      1     Joshua Lonaker  United States of America
2      2      Dakota Blanco  United States of America
3      3    Natasha Yarusso  United States of America
4      4     Brooke Cazares                    Brazil
..   ...                ...                       ...
302  302        Austin Haas  United States of America
303  303    Madison Fithian  United States of America
304  304  Zachary Mulvahill  United States of America
305  305   Eliana Michelsen  United States of America
306  306    Dane Whittemore                    Canada

[307 rows x 3 columns]
   id              name               nationality                 city  \
0   0         Kiana Lor                     China               Suzhou
1   1    Joshua Lonaker  United States of America        Santa Clarita
2   2     Dakota Blanco  United States of America              Oakland
3   3   Natasha Yarusso  United States of America        Castro Valley
4   4    Brooke Cazares                    Brazil  São José dos Campos
5   5  Rochelle Johnson  United States of America         Indianapolis
6   6        Joey Abreu                     China             Shenyang
7   7    Preston Suarez                    Brazil            São Paulo
8   8          Lee Dong               Philippines               Manila
9   9     Maa'iz al-Dia                    Turkey             Istanbul

   latitude  longitude gender  ethnic.group  age  english.grade  math.grade  \
0     31.31     120.62      F           NaN   22            3.5         3.7
1     34.39    -118.54      M           NaN   22            2.9         3.2
2     37.80    -122.27      F           NaN   22            3.9         3.8
3     37.69    -122.09      F           NaN   20            3.3         2.8
4    -23.18     -45.88      F           NaN   21            3.7         2.6
5     39.77     -86.16      F           NaN   21            3.4         3.1
6     41.79     123.43      M           NaN   22            3.7         3.9
7    -23.47     -46.67      M           NaN   22            3.8         3.7
8     14.60     120.98      F           NaN   24            3.9         3.6
9     41.02      28.96      M           NaN   22            2.4         2.8

   sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
0             3.1             1.0                 4                 4.0
1             3.6             5.0                 5                 4.0
2             3.2             5.0                 3                 3.0
3             3.2             5.0                 5                 2.0
4             3.4             1.0                 4                 4.0
5             3.7             5.0                 2                 4.0
6             3.6             2.0                 5                 5.0
7             3.6             2.0                 5                 5.0
8             3.2             2.0                 4                 3.0
9             3.8             3.0                 5                 5.0

   refletter.rating
0                 4
1                 5
2                 4
3                 4
4                 5
5                 4
6                 5
7                 4
8                 5
9                 4
      id               name               nationality         city  latitude  \
302  302        Austin Haas  United States of America     Columbus     39.96
303  303    Madison Fithian  United States of America  Los Angeles     34.05
304  304  Zachary Mulvahill  United States of America  Los Angeles     34.05
305  305   Eliana Michelsen  United States of America      Oakland     37.80
306  306    Dane Whittemore                    Canada      Toronto     43.67

     longitude gender  ethnic.group  age  english.grade  math.grade  \
302     -83.00      M           NaN   20            3.6         3.7
303    -118.24      F           NaN   20            3.6         3.9
304    -118.24      M           NaN   20            3.2         3.4
305    -122.27      F           NaN   23            3.0         2.8
306     -79.42      M           NaN   21            3.8         3.2

     sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
302             3.1             5.0                 4                 5.0
303             4.0             5.0                 5                 5.0
304             3.9             5.0                 5                 5.0
305             2.9             5.0                 4                 4.0
306             4.0             5.0                 5                 4.0

     refletter.rating
302                 5
303                 3
304                 3
305                 5
306                 5

### Label-based Indexing (.loc[])
- .loc[] is used for selecting rows and columns by labels
- We can use single labels, lists of labels, or slices of labels

In [14]:
# Selecting rows based on label
students = pd.read_csv('data/student-dataset.csv')
first_row = students.loc[1]
first_two_rows = students.loc[0:1]
print(first_row)                    # Row with label 1 (index) labels can be string, date etc
print(first_two_rows)                  # Rows with labels 0 to 1

# # Selecting specific rows to columns
first_five_stds_with_name_to_nationality = students.loc[0:4,'name':'nationality']
print(first_five_stds_with_name_to_nationality)         # Rows 0 to 2, columns name to nationality

# select only particular rows and columns
first_and_second_row_with_name_and_gender = students.loc[[5, 20], ['name', 'gender']]
# Rows 6th and 21th, columns name and gender
first_and_second_row_with_name_and_gender

id                                           1
name                            Joshua Lonaker
nationality           United States of America
city                             Santa Clarita
latitude                                 34.39
longitude                              -118.54
gender                                       M
ethnic.group                               NaN
age                                         22
english.grade                              2.9
math.grade                                 3.2
sciences.grade                             3.6
language.grade                             5.0
portfolio.rating                             5
coverletter.rating                         4.0
refletter.rating                             5
Name: 1, dtype: object
   id            name               nationality           city  latitude  \
0   0       Kiana Lor                     China         Suzhou     31.31
1   1  Joshua Lonaker  United States of America  Santa Clarita     34.39

   longitude gender  ethnic.group  age  english.grade  math.grade  \
0     120.62      F           NaN   22            3.5         3.7
1    -118.54      M           NaN   22            2.9         3.2

   sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
0             3.1             1.0                 4                 4.0
1             3.6             5.0                 5                 4.0

   refletter.rating
0                 4
1                 5
              name               nationality
0        Kiana Lor                     China
1   Joshua Lonaker  United States of America
2    Dakota Blanco  United States of America
3  Natasha Yarusso  United States of America
4   Brooke Cazares                    Brazil

                name gender
5   Rochelle Johnson      F
20        Rojesh Her      M

<!--  -->

### Integer-location Based Indexing
- .iloc[] is **used** for selecting rows and columns by integer index positions
- Similar to .loc[], we can use single integers, lists of integers, or slices

In [15]:
# Selecting rows based on index positions
print(students.iloc[1])                   # Second row (index 1)
print(students.iloc[0:3])                 # Rows at index positions 0 to 2

# Selecting specific rows and columns
print(students.iloc[0:2, 0:2])            # Rows 0 to 1, columns 0 to 2
print(students.iloc[[0, 2], [0, 2]])      # Rows 0 and 2, columns 0 and 2

id                                           1
name                            Joshua Lonaker
nationality           United States of America
city                             Santa Clarita
latitude                                 34.39
longitude                              -118.54
gender                                       M
ethnic.group                               NaN
age                                         22
english.grade                              2.9
math.grade                                 3.2
sciences.grade                             3.6
language.grade                             5.0
portfolio.rating                             5
coverletter.rating                         4.0
refletter.rating                             5
Name: 1, dtype: object
   id            name               nationality           city  latitude  \
0   0       Kiana Lor                     China         Suzhou     31.31
1   1  Joshua Lonaker  United States of America  Santa Clarita     34.39
2   2   Dakota Blanco  United States of America        Oakland     37.80

   longitude gender  ethnic.group  age  english.grade  math.grade  \
0     120.62      F           NaN   22            3.5         3.7
1    -118.54      M           NaN   22            2.9         3.2
2    -122.27      F           NaN   22            3.9         3.8

   sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
0             3.1             1.0                 4                 4.0
1             3.6             5.0                 5                 4.0
2             3.2             5.0                 3                 3.0

   refletter.rating
0                 4
1                 5
2                 4
   id            name
0   0       Kiana Lor
1   1  Joshua Lonaker
   id               nationality
0   0                     China
2   2  United States of America

### Single Value Access (.at[] and .iat[])
- .at[] is used for accessing a single scalar value by label.
- .iat[] is for accessing by index position.

In [16]:
# Using .at[] to access single value by label
print(students.at[1, 'name'])                # Value in row 2, column 'name'

# Using .iat[] to access single value by position
print(students.iat[5, 1])                 # Value in row 6, column 1

Joshua Lonaker
Rochelle Johnson

### Create new Dataframe from the students data, with name, nationality and grades in english and maths

In [17]:

students.loc[100:,['name','nationality','math.grade','english.grade']]

                    name               nationality  math.grade  english.grade
100       Rachel Bakeman  United States of America         3.7            3.9
101  Mamdooh el-Moustafa                  Pakistan         2.8            3.3
102       Lindsey Carter  United States of America         3.9            3.2
103         Duncan Kruse  United States of America         3.8            3.7
104      Callahan Foster                    Canada         3.0            3.2
..                   ...                       ...         ...            ...
302          Austin Haas  United States of America         3.7            3.6
303      Madison Fithian  United States of America         3.9            3.6
304    Zachary Mulvahill  United States of America         3.4            3.2
305     Eliana Michelsen  United States of America         2.8            3.0
306      Dane Whittemore                    Canada         3.2            3.8

[207 rows x 4 columns]

### Select First 100 rows and 'name','ethinic group' columns from the given students data

# Filtering
- Logical operators (>, <, ==,  !=)
- Multiple logical operators (& (AND) and | (OR))
- Str ancessor, Isin, contains, between, startWith
- Tilde (~)
- Query
- Nlargest and nsmallest
- Loc and iloc

### Logical Operators

In [18]:
from IPython.display import display
# students with grade less than 2
stds_failed_in_english = students[students['math.grade']<2]
display(stds_failed_in_english)
# students with grade greater than 3.5
stds_passed_in_english = students[students['english.grade']>3.5]
display(stds_passed_in_english)

# select chinese students with grade in english greater than 3.6
topper_chinese_students = students[students['nationality']=='China']    
topper_chinese_students[topper_chinese_students['english.grade']>3.6]
topper_chinese_students

Empty DataFrame
Columns: [id, name, nationality, city, latitude, longitude, gender, ethnic.group, age, english.grade, math.grade, sciences.grade, language.grade, portfolio.rating, coverletter.rating, refletter.rating]
Index: []

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5
6,6,Joey Abreu,China,Shenyang,41.79,123.43,M,NaN,22,3.7,3.9,3.6,2.0,5,5.0,5
7,7,Preston Suarez,Brazil,São Paulo,-23.47,-46.67,M,NaN,22,3.8,3.7,3.6,2.0,5,5.0,4
8,8,Lee Dong,Philippines,Manila,14.60,120.98,F,NaN,24,3.9,3.6,3.2,2.0,4,3.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
296,296,Brittany Fernandez,Mexico,Zamora,19.98,-102.27,F,NaN,23,3.9,3.7,2.9,4.0,3,4.0,4
297,297,Cody Smith,United States of America,Charlotte,35.23,-80.84,M,NaN,23,3.8,3.5,3.9,5.0,5,2.0,5
302,302,Austin Haas,United States of America,Columbus,39.96,-83.00,M,NaN,20,3.6,3.7,3.1,5.0,4,5.0,5
303,303,Madison Fithian,United States of America,Los Angeles,34.05,-118.24,F,NaN,20,3.6,3.9,4.0,5.0,5,5.0,3
306,306,Dane Whittemore,Canada,Toronto,43.67,-79.42,M,NaN,21,3.8,3.2,4.0,5.0,5,4.0,5

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
6,6,Joey Abreu,China,Shenyang,41.79,123.43,M,NaN,22,3.7,3.9,3.6,2.0,5,5.0,5
21,21,David Weber,China,Peking,39.93,116.39,M,NaN,20,3.9,3.9,3.9,2.0,3,4.0,5
24,24,Sila Nguyen,China,Hebi,35.90,114.19,M,NaN,23,2.8,3.5,3.5,4.0,5,4.0,4
61,61,Colin Lemont,China,Shanghai,31.05,121.40,M,NaN,21,3.6,4.0,3.1,4.0,4,5.0,4
76,76,Sourinthone Tran,China,Wuhan,30.58,114.27,M,NaN,21,3.5,3.9,3.4,4.0,4,4.0,5
162,162,Rebecca Ah Fat,China,Tangshan,37.33,114.70,F,NaN,22,1.8,3.8,4.0,4.0,4,3.0,4
176,176,Surya Ky,China,Tangshan,37.33,114.70,M,NaN,21,3.7,4.0,3.8,4.0,4,4.0,5
189,189,Emma Kim,China,Hengshui,37.73,115.70,F,NaN,22,2.8,3.9,3.8,2.0,4,4.0,4
194,194,Chue Fue Richter,China,Qiqihar,47.34,123.97,M,NaN,23,3.0,3.6,1.4,4.0,5,3.0,4
214,214,Christian Chow,China,Handan,36.57,114.53,M,NaN,21,2.6,3.9,3.4,4.0,5,5.0,5
218,218,Nicole Patria,China,Chongqing,29.56,106.55,F,NaN,24,3.9,3.3,3.0,2.0,3,5.0,5
232,232,Anna Yoshimura,China,Rizhao,35.39,119.55,F,NaN,20,3.5,3.8,3.9,4.0,5,5.0,2

### Multiple Logical Opertors

In [19]:
from IPython.display import display
#  students having grades greater than 3.5 in all subjects
topper_students = students[ (students['math.grade'] > 3.6)  & (students['english.grade'] > 3.6) ]

# students with grade than 3.8 in at least one subject
std_with_highest_mark = students[(students['english.grade']>=3.8) | (students['math.grade']>=3.8) ]
display(std_with_highest_mark)

# find all indian female students 
# with age greater thant 23 and grade in maths greater than 4
students[]

SyntaxError: invalid syntax (2277109942.py, line 11)

### str,Isin, contains, between, startWith

In [ ]:
# students name starts with 'J'
stds_with_name_j = students[students.name.str.startswith('J')]
stds_with_name_j.head()

stds_with_name_gimmy = students[students.name.str.contains('Gimmy')]
print(stds_with_name_gimmy)
# students with maths.grade  between 4 and 5
stds_with_name_j = students[students['math.grade'].between(4,5)]
stds_with_name_j.head()

# chinese or american students
chinese_or_american_students = \
            students[students['nationality'].isin(['China', 'America'])]
chinese_or_american_students

# students with age between 20-24

### Tilde(~)

In [ ]:
# Filter students with age less than 20 and greater than 24
stds_with_age_less_than_20 = students[~students['age'].between(20, 24)]
stds_with_age_less_than_20.head()

### Query

In [23]:
# Filter students with age above 25 and gender is 'male'
import pandas as pd
students = pd.read_csv('./data/student-dataset.csv')
students.head()
query_filter = students.query("age > 25 and gender == 'M'")
query_filter.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
83,83,Luke Davey,United States of America,Los Angeles,34.05,-118.24,M,NaN,26,3.8,3.4,3.7,5.0,4,5.0,3

### nlargest and nsmallest
Use nlargest and nsmallest to get rows with the top or bottom values in a column

In [24]:
# Get top 3 students with the highest grades in english
top_3_marks = students.nlargest(3, 'english.grade')
print(top_3_marks)
# Get 2 students with the lowest grades in english
bottom_2_marks = students.nsmallest(2, 'english.grade')
# get top 5 students with highest marks in Math
math_topper = students.nlargest(5,'math.grade')
math_topper

      id             name          nationality              city  latitude  \
15    15    Brittany Sath                Japan             Tokyo     35.69
68    68  Gabrielle Smith  Korea (Republic of)             Seoul     37.60
120  120    Meghan Arnold   Russian Federation  Saint Petersburg     59.89

     longitude gender  ethnic.group  age  english.grade  math.grade  \
15      139.75      F           NaN   21            4.0         3.9
68      126.98      F           NaN   23            4.0         3.0
120      30.26      F           NaN   24            4.0         3.9

     sciences.grade  language.grade  portfolio.rating  coverletter.rating  \
15              3.7             3.0                 5                 3.0
68              2.8             3.0                 2                 2.0
120             3.3             3.0                 5                 3.0

     refletter.rating
15                  5
68                  4
120                 3

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
11,11,Sasha Jansen,United States of America,Chicago,41.85,-87.65,F,NaN,21,1.7,4.0,3.6,5.0,4,4.0,5
37,37,Katrina Saito,Japan,Tokyo,35.69,139.75,F,NaN,22,3.8,4.0,3.7,4.0,5,4.0,5
47,47,Zoe Kern,United States of America,West Jordan,40.61,-111.94,F,NaN,22,2.1,4.0,3.4,5.0,4,5.0,4
61,61,Colin Lemont,China,Shanghai,31.05,121.40,M,NaN,21,3.6,4.0,3.1,4.0,4,5.0,4
117,117,Marisa Ramey,Mexico,Mexico,19.43,-99.14,F,NaN,22,3.2,4.0,3.8,4.0,3,3.0,4

### loc and iloc

In [ ]:
# Using `loc` to select rows with IDs greater than 2
loc_filter = students.loc[students['id']> 2,['id','name']]
loc_filter.head()

   id              name
3   3   Natasha Yarusso
4   4    Brooke Cazares
5   5  Rochelle Johnson
6   6        Joey Abreu
7   7    Preston Suarez

# Data Transformation and Mapping
- **apply**: allows us to apply a function to each element, row, or column in a DataFrame or Series
- **map**: is  used to map values in a Series according to a dictionary or another Series
- **replace**: replace allows for replacing specific values in the DataFrame with new value
- **astype**: this is used to convert data type
- **pipe**: it allows chaining and using complex functions that operate on the entire DataFrame. This can be used for complex transformation operation

### apply

In [30]:
import pandas as pd
# convert grades to scale of 100
students = pd.read_csv('data/student-dataset.csv')
students['marks_in_english'] = students['english.grade']\
    .apply(lambda grade: grade*20)

# add new column to students data frame for pass and fail
# Pass if marks_in_english >= 40 else fail
students['result']  = students['marks_in_english']\
    .apply(lambda marks: "Pass" if marks>=40 else "Fail")

def calculate_grade(marks):
    if marks>=80:
        return 'A'
    elif marks>=60 and marks<80:
        return 'B'
    else:
        return 'C'


students['grade']  = students['marks_in_english']\
    .apply(calculate_grade)
students.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,marks_in_english,result,grade
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4,70.0,Pass,B
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5,58.0,Pass,C
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4,78.0,Pass,B
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4,66.0,Pass,B
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5,74.0,Pass,B

### map

In [31]:
import pandas as pd
students = pd.read_csv('data/student-dataset.csv')
students['gender'] = students['gender'].map({'M':'Male','F':'Female'}) 
students['nationality'] = students['nationality']\
    .map({'Nepal':'Gorkhali','China':'Chinese','America':'American'})
students.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,Chinese,Suzhou,31.31,120.62,Female,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,NaN,Santa Clarita,34.39,-118.54,Male,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,NaN,Oakland,37.80,-122.27,Female,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,NaN,Castro Valley,37.69,-122.09,Female,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,NaN,São José dos Campos,-23.18,-45.88,Female,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

### replace

In [ ]:
# replace name 'John Doe' with 'JaiRam' (replace specific value)
students['name'] = students['name'].replace({'John Deo':'JaiRam'})
students.head()

### astype

In [ ]:
# Convert 'english.grade' column to int
students['english.grade'] = students['english.grade'].astype(int)
# Convert 'math.grade' column to string
students['math.grade'] = students['math.grade'].astype(str)

# convert to datetime
# students['dob'] = pd.to_datetime(students['dob'])

students.head()

### pipe

In [ ]:
 
def calculate_final_grades(df):
    df['final_grades'] =  \
        df['english.grade'].astype(float)+ df['math.grade'].astype(float) /2
    return df


students['grade_in_math'] = students['math.grade'].apply(lambda x : 'A' if x>80 else 'B')
students = students.pipe(calculate_final_grades)
students.tail() # last 5 items

# Data Cleaning and Manipulation
- Handle Missing Data
- Handle Duplicates
- One-Hot-Encoding
- Normalization 

![Benefits of Data Cleaning](assets/data-cleaning.png)

### Handle Missing Data
- Remove Rows Containing Missing Values ``(df.dropna())``
    - ``dropna(axis=0)`` removes rows containing at least one missing value
    - ``(dropna(axis=1))`` Removes columns containing at least one missing value 
- Replace Missing Values ``(df.fillna())``
    - **Replace with specific value**: ``(df.fillna(value))`` 
    - **Backward Fill, Forward Fill**: ``(df.fillna(value,method='bfill')) (df.fillna(value,method='ffill'))`` 
    - **Fill individual column with specified value**: ``(df.fillna({'height':150,'weight:60})`` 
    - **Fill with average, Interpolation etc.**:

In [ ]:
from IPython.display import display

students = pd.read_csv('data/students-data.csv')

display(students.head())
students.dropna(axis=0,how='any',inplace=True) 
# (axis=0 default) drop rows with NaN  

students =students.fillna(1)  # replace missing values with 1
display(students.head())

students.fillna(method='ffill') # fill with previous row value
students.fillna(method='bfill') # fill with next row
students['english.grade'].fillna(50) # ony fill empty value of english.grade column
students.fillna({'english.grade':50,'math.grade':60}) # replace english.grade with 50 if its empty and gender with Male
df_interpolated = students.interpolate()
students.fillna(df_interpolated)
students['math.grade'].fillna (students['math.grade'].mean())

### Handle Duplicate Data
- Check Duplicates
- Drop Duplicates

In [ ]:
duplicates = students.duplicated() # check duplicate
students.drop_duplicates() # drop duplicate
duplicates

### One-Hot-Encoding
- One Hot Encoding is a method for converting categorical variables into a binary format. It creates new binary columns (0s and 1s) for each category in the original variable. Each category in the original column is represented as a separate column, where a value of 1 indicates the presence of that category, and 0 indicates its absence
For example we replace the country name with numerical value
e.g. America = 1,
India=2
Nepal=3

In [ ]:

students = pd.read_csv('data/student.csv')
df_pandas_encoded = pd.get_dummies(students, columns=['class'])
display(df_pandas_encoded)

### Data Normalization 
Data normalization involves adjusting measurement values of different scales to a common scale. Normalization is only applicable to numerical columns.

![Normalization Techniques](assets/normalization-technique.png)

There are five common normalization methods:

1. Single feature scaling
2. Min-max scaling
3. Z-score normalization
4. Log scaling
5. Clipping

In [ ]:
import numpy as np
salt = np.log(30)
gold = np.log(150000)
print(salt,gold)

### Single Feature Scaling
Single feature scaling transforms each value in a column into a number between 0 and 1
### Min-Max Scaling
This scales the data to a specific range, typically [0, 1]. The formula is:
x_new = x- min(x) / (max(x)-min(x))
​
###  Z-score Normalization
This normalization method transforms the data so that it has a mean of 0 and a standard deviation of 1. 

x_new =( x - μ) / σ 

Where: μ = mean and σ  = SD
 
 ### Log Scaling
 This method uses the logarithm to scale the data, which is useful when dealing with data that has a large range or is heavily skewed

 x_new = log(x+1)

 ### Clipping
 Clipping is a technique to limit the range of data by setting lower and upper bounds. It’s useful for handling outliers.

In [ ]:
import numpy as np
import pandas as pd
products = pd.read_csv('data/product-data.csv')
display(products.head())
# Single Feature Scaling
products['Sales_Single_Scale'] = products['Sales'] / products['Sales'].max()

# log
products['Sales_Log_Scale'] = np.log1p(products['Sales'])

# clipping
products['Discount_Clipped'] = products['Discount_Percentage']\
    .clip(lower=5, upper=15)

products.head()

## Normalization

In [ ]:
import pandas as pd
import numpy as np
data = {
 "item":['Biscuit','Tv','Mobile'],
 "price":[100,20000,200000],
}
data_frame = pd.DataFrame(data)
data_frame['max_min_value'] = data_frame['price'] - data_frame['price'].min()/ \
    (data_frame['price'].max()-data_frame['price'].min())


mean = data_frame['price'].mean()
sd = data_frame['price'].std()
data_frame['z_score_value']  = (data_frame['price'] - mean) / sd
data_frame['log_value'] = np.log10( data_frame['price'])
data_frame

      item   price  max_min_value  z_score_value  log_value
0  Biscuit     100        99.9995      -0.665346    2.00000
1       Tv   20000     19999.9995      -0.484631    4.30103
2   Mobile  200000    199999.9995       1.149977    5.30103

# Grouping & Aggregate

- Groping consists of three operations
    - Split
    - Apply
    - Combine

![Grouping](./assets/grouping.png)

### Group By

In [14]:
import numpy as np
from IPython.display import display
import pandas as pd

students = pd.read_csv('data/student-dataset.csv')

# group data based on Gender
gender_data = students.groupby('gender')
display(gender_data.count())

gender_data['english.grade'].mean() #  

group_by_nationality = students.groupby('nationality')
display(group_by_nationality['math.grade'].mean())

,id,name,nationality,city,latitude,longitude,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
gender,,,,,,,,,,,,,,,
F,152,152,152,152,152,152,0,152,152,152,152,152,152,152,152
M,151,151,151,151,151,151,0,151,151,151,151,151,151,151,151
other,4,4,4,4,4,4,0,4,4,4,4,4,4,4,4

nationality
Bangladesh                  3.900000
Brazil                      3.377778
Canada                      3.014286
Chile                       3.700000
China                       3.784615
Colombia                    3.580000
Cuba                        2.800000
Dominican Republic          3.800000
Egypt                       3.500000
El Salvador                 2.900000
Germany                     3.500000
India                       3.275000
Japan                       3.538462
Korea (Republic of)         3.066667
Mexico                      3.387500
Morocco                     3.600000
Myanmar                     3.400000
Netherlands                 3.500000
Nicaragua                   3.700000
Pakistan                    2.933333
Peru                        3.100000
Philippines                 3.600000
Poland                      3.800000
Russian Federation          3.383333
Spain                       3.750000
Thailand                    3.900000
Tunisia                     3.100000
Turkey                      2.700000
Ukraine                     3.300000
United Kingdom              3.150000
United States of America    3.417098
Name: math.grade, dtype: float64

### Aggregation
- count() – Number of non-null observations
- sum() – Sum of values
- mean() – Mean of values
- median() – Arithmetic median of values
- min() – Minimum
- max() – Maximum
- mode() – Mode
- std() – Standard deviation
- var() – Variance

# Sorting

### Sort By Index

### Sort By Value
- Ascending
- Descending
- Sorting by Date
- Sorting with key Function

In [ ]:
students = pd.read_csv('data/student-dataset.csv')
new_sorted_data = students.sort_values(by=['name'],ascending=False)
display(new_sorted_data.head())

# sort by  math grade
students.sort_values(by='math.grade',ascending=False,inplace=True)
students.head()

### Sorting By Date

If we want sort data based on datetime we need to convert the datetime to datetime object

In [ ]:

data = pd.read_csv('data/student-admission.csv')

# convert to datetime
data['AdmissionDate']  = pd.to_datetime(data['AdmissionDate'])

# sort by AdminssionDate
sorted_by_date = data.sort_values(by=['AdmissionDate','Name'],ascending=True)
sorted_by_date

### Sorting with Key Function

In [ ]:
sorted_key_data = data.sort_values(by='Name', key=lambda x: x.str.len(),ascending=False)
sorted_key_data